baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Carbontribe"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Carbontribe"
  description: "Carbon removal digital assets, free from greenwashing"
  images: 
    - "images/main_company_logo.png"

  logo: "images/logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Kesklinna Linnaosa, Ahtri 12,, 15551, Tallinn, Estonia"

  contact:
    - "kyano@carbontribe.me"

  copyright: "© 2024 Carbontribe Labs OÜ All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "News"
      url: "/blog"
      weight: 2

  # buttons:
    # - name: "Read our lightpaper"
    #   url: 
    #   # url: "https://carbontribe.gitbook.io/carbontribe-lite-paper/light-papaer-ver.1.0/general-information"
    #   weight: 5
    #   pre: "btn btn-primary text-light"
    #   target: "_blank"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "News"
      url: "/blog"
      weight: 2

taxonomies:
  series: "series"
  tags: "tags"
