baseURL: "https://www.carbontribe.me/"
theme: "up-business-theme"
languageCode: "en-us"

title: ""

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Carbontribe"
  description: "Next-Gen Carbon Finance AI-Powered, Data-Driven & Verified"
  images: 
    - "images/preview.png"

  logo: "images/logo.png"

  favicons:
    themeColor: ""
    backgroundColor: ""
    faviconColor: "#000000"

  social:
    dribbble: "#"
    linkedin: "https://www.linkedin.com/company/carbontribe/"

  location:
    - "Kesklinna Linnaosa, Ahtri 12,, 15551, Tallinn, Estonia"

  contact:
    - "team@carbontribe.me"

  copyright: "© 2024 Carbontribe Labs OÜ All Rights Reserved"

menus:
  main:
    - name: "Projects"
      url: "/projects"
      weight: 1

    - name: "Standards"
      url: "/standards"
      weight: 2

    - name: "Carbontribe Book"
      url: "/book/introduction"
      weight: 3

    - name: "About us"
      url: "/aboutus"
      weight: 4
  
    - name: "Collaborate"
      weight: 5
      identifier: "our-process"  # Unique ID for dropdown

    - name: "as a partner"
      url: "/book/for_partners"
      parent: "our-process"
      weight: 1

    - name: "as a buyer"
      url: "/book/for_buyers"
      parent: "our-process"
      weight: 2

    - name: "News"
      url: "/blog"
      weight: 6

  # buttons:
    # - name: "Read our lightpaper"
    #   url: 
    #   # url: "https://carbontribe.gitbook.io/carbontribe-lite-paper/light-papaer-ver.1.0/general-information"
    #   weight: 5
    #   pre: "btn btn-primary text-light"
    #   target: "_blank"

  footer:
    - name: "Projects"
      url: "/projects"
      weight: 1

    - name: "Standards"
      url: "/standards"
      weight: 2

    - name: "Carbontribe Book"
      url: "/book/introduction"
      weight: 3

    - name: "About us"
      url: "/aboutus"
      weight: 4
  
    - name: "News"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true