baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Carbontribe"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Carbontribe"
  description: "Buy carbon credits without greenwashing"
  images: 
    - "images/main_company_logo3.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    linkedin: "https://www.linkedin.com/company/carbontribe/"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "© 2024 Carbontribe Labs OÜ All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "News"
      url: "/blog"
      weight: 2

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "News"
      url: "/blog"
      weight: 2

taxonomies:
  series: "series"
  tags: "tags"
